### ISSUE TITLE
Broken under Wagtail 4.1

### ISSUE THREAD

**Issue by dexedge** [donhauser/wagtail-pdf#11] opened 2023-08-15 21:28 UTC
My site has been using wagtail-pd-view  for a while now, and it has been working fine under Wagtail v. 2.15.3. This week I finally had time to begin upgrading. I'm now at Wagtail 4.1.3, and everything else works fine, but pdf generation is broken. The error I'm currently getting is:

Exception Value: 'NoneType' object has no attribute 'as_view'
Exception Location: [...] /myenv/lib/python3.10/site-packages/wagtail_pdf_view/mixins.py, line 273, in get_pdf_view

I've been upgrading incrementally. I'm not positive, but I think pdf generation already broke at Wagtail 3.0?

Any help or ideas would be appreciated.

**Comment by donhauser** [comment] 2024-10-09 12:31
Hey,

this is a quite late response. Nevertheless, I've wanted to document that the new version [1.0.0](https://github.com/donhauser/wagtail-pdf/releases/tag/1.0.0) is now tested against Wagtail 4 and Wagtail 5. In general the previous version 0.2.1 was just partially broken under Wagtail 4, because of CORS issues in the PDF preview.

For further reference: The particular exception here rather hinted at a bad configuration of `PDF_VIEW_PROVIDER` or `DEFAULT_PDF_VIEW_PROVIDER` (both removed now), which could be caused by a missing _django-weasyprint_ installation. In the updated version, this is fixed by using a proper PDF view registry and by adding _django-weasyprint_  as obligatory requirement.

**Closed as completed by donhauser** 2024-10-09 12:31 UTC
